# Generated by Django 4.0.10 on 2024-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='event_date',
            new_name='session_date',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(default='default description', max_length=200),
        ),
    ]
