# Generated by Django 4.0.10 on 2024-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_instrument_alter_session_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='display_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
