# Generated by Django 4.0.10 on 2024-03-09 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='goals',
            field=models.TextField(default='Insert Goal'),
        ),
        migrations.AddField(
            model_name='session',
            name='instrument_preference',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('drums', 'Drums'), ('bass', 'Bass')], default='Instrument Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='Instrument Choice', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
